### ISSUE TITLE
Bugs related to fights and gangs

### ISSUE THREAD

**Issue by nroutasuo** [nroutasuo/level13#13]
Description by @Pimhazeveld in #11 

> Defeating an enemy has a chance of turning the screen black.
>
> option to fight raids sometimes disappear after losing to them but later reappears.
>
> gangs randomly disappear when coming near them and reappear later. I mean, just look at this, how did I even get past the gang? https://i.imgur.com/wf9HGCx.png
>
> loot gained from gangs is not actually added to your bag and can go over your maximum carry limit.

**Comment by Katorone** [comment]
In addition to this

- Sometimes the 'continue' button doesn't work (it can be clicked but doesn't close the window).  I think this happens when the loot is more than the inventory can hold.  Though this doesn't happen all the time.  This requires a refresh.

- Sometimes a fight won't have the buttons to fight or flee, requiring a refresh.

**Comment by praxiq** [comment]
I can confirm I saw the "one-way gang" issue on the first level in my game. It said something like "The gang to the north has already been cleared" (even though I hadn't fought it) but after I went north, I was unable to go back south because the gang was present.

**Comment by desci** [comment]
Also present in #7

**Comment by nroutasuo** [comment]
These issues should all be fixed in the upcoming update. Thanks for the reports and details!
