### ISSUE TITLE
upgrade unlocking order BUG

### ISSUE THREAD

**Issue by rm3000** [nroutasuo/level13#177]
**Game version**
0.3.2

**Browser**
chrome

**Description**
the newest updatelog said "Adjust upgrade unlocking order (ensure unlocking Knife doesn't block Compass)" but it still happen....my map seed is 6294. and i finish all grid in lv13 and lv12 .
but still need 27 points to unlock compass.this is my savedata
[13lvsave.txt](https://github.com/nroutasuo/level13/files/6040346/13lvsave.txt)

**Comment by nroutasuo** [comment]
Thank you for the save!
Did you start this game on the previous version? If so, you might have gotten stuck because the balancing changed mid-game.
You should have gotten a total of 290 evidence from the levels you've explored, and spent 161 evidence unlocking the upgrades you've currently bought.
Regardless, the [save fix tool](https://nroutasuo.github.io/level13/tools.html) should help you continue.

**Comment by Nintai** [comment]
Your world seed: 6218
Current version: 0.3.2 (alpha)
[Nintai Level 13.txt](https://github.com/nroutasuo/level13/files/6061801/Nintai.Level.13.txt)

I scouted every single coordinate on both level 12 and 13 that i could scout.

Im currently stuck because i need 56 evidence to unlock Textile Arts and only have 43.

The unscouted coordinates i have on level 12 require me to have more warmth, which i cant get without the research.

**Comment by nroutasuo** [comment]
Thanks for reporting! Looks like I need to give the balancing some more thought. In the meanwhile, I cheated you some itmes that should help you continue:
[nintai-fixed.txt](https://github.com/nroutasuo/level13/files/6064634/nintai-fixed.txt)

**Comment by nroutasuo** [comment]
The upgrade order is adjusted for the upcoming version, closing this ticket now.
