### ISSUE TITLE
Invalid route back to camp

### ISSUE THREAD

**Issue by primeprover** [nroutasuo/level13#20]
It looks like the game will let you automatically go back to camp via routes that don't exist as long as you are close enough as the crow flies to the camp.

**Comment by Pimhazeveld** [comment]
Yes, the game allows you to walk to the camp using the least amount of staps you can take. Even if this means going straight through walls.

This doesn't take stamina multiplies from boots in effect though.

**Comment by praxiq** [comment]
I assumed this was deliberate, not an issue. I guess it doesn't make much sense from a story perspective, but from a gameplay perspective it's nice. It adds a sense of variety to exploration - two areas might both be 20 steps away from the starting point, but one is a lot more dangerous to explore than the other, because the amount of resources needed to return home is different.

**Comment by nroutasuo** [comment]
It was actually not deliberate. Pathfinding has been added for this and in the next update the cost to return to camp will reflect the actual shortest passable route.
