### ISSUE TITLE
Level generation: seemingly blocked on level 6 without random scavenge/trade

### ISSUE THREAD

**Issue by joshtriplett** [nroutasuo/level13#219]
**Game version**
0.3.3 (alpha)

**Browser**
Firefox 95

**Description**
world seed: 2567

On level 6, I've explored everywhere reachable without going through `Environment: cold (40)` sectors. I've lockpicked everything reachable. With all the warmest equipment craftable (winter parka / work gloves / wool hat / basic pants / T-shirt, I can only get to warmth 38. There's a broken elevator to level 5 accessible, but I've only found 2 of 3 blueprints for Elevator Mechanics.

I looked at `ItemData.json`, and `campOrdinalRequired`, and it looks like it should be possible to find the "Factory uniform pants" and "Factory uniform shirt", and the former (not the latter) would be enough to push warmth high enough for further exploration. But there are no more locales to search in. Is the expectation to just wait for a random trader, or wait until a random scavenge turns it up?

**Comment by nroutasuo** [comment]
Thank you for reporting. You do indeed need the Factory Uniform Pants to continue. I've changed the world generation quite a bit since the live version so I am not going to dig too deep into why you haven't found them yet. Hopefully this already works better in the next version.

Yoy will have a higher chance to find good equipment in the following locations (when scavenging there for the first time) - check them out if you haven't yet:
5W 0S, 6W 1S, 5W 1S, 5W 6S, 7E 8S, 7E 9S

If you're totally stuck, feel free to share your save and I'll just cheat them for you.

**Comment by joshtriplett** [comment]
@nroutasuo Thanks for the confirmation; that helps. I'd been assuming that in general the items and blueprints obtained from lockpickable locations were the primary gate to progress, and it helps to know that sometimes equipment needs to come from other sources. I ended up getting them from a trader.
