### ISSUE TITLE
World Seed 3506 Impossible

### ISSUE THREAD

**Issue by utopianfiat** [nroutasuo/level13#45]
Not sure if there's some kind of tag for impossible world issues at this point.

> Note: if you're trying to report an impossible seed issue, and you don't know how to find your world seed, run this snippet in the console (just the first line, without the `>`):

```
> JSON.parse(window.localStorage.getItem("gameState"))['worldSeed']
3506
```

Characteristics:
- Level 13 is unremarkable. One upward staircase, one downward staircase.
- Level 12 is unremarkable, but has two downward staircases.
- Level 11's camp is in bright light. One downward staircase, two upward staircases.
- Level 10 has no camp. One downward staircase, one upward staircase.
- Level 9 has no accessible camp (?). One upward staircase. Map reports "there are many unexplored streets".

It might help tide things over to Beta if the World Generator actually simulates walking the world without thirst/hunger/stamina just to prove that you can theoretically reach everything.

**Comment by nroutasuo** [comment]
Thanks for the details! I'll definitely look over the World Generator before next update.

**Comment by nroutasuo** [comment]
This has been fixed in current master and will be in the next update. Thanks again for reporting,

The problem was that some levels were created disconnected, so on level 9 you could never access most of the sectors. I'll definitely look into doing some kind of an automatic sanity check on generated levels in the future.
