### ISSUE TITLE
Number of camps

### ISSUE THREAD

**Issue by mavion** [nroutasuo/level13#98]
**Game version**
v. 0.2.3 (alpha)

**Browser**
Mozilla Firefox

**Description**
I have currently explored down to level 4, which has radiation. My last and fourth camp was on level 8. Level 6 had the blueprints for bridge and level 5 has a bunch more, but I can't see what since I do not have the stamina for it.
From what I can tell from looking at the code, the intention is for those blueprints to be unlocked on levels with camps. Is the intention that we should only be able to get 4 camps for now?

**Comment by nroutasuo** [comment]
There is definitely quite a few features (including upgrades) in the game that are still locked due to the camp limit. The late game simply isn't balanced or coherent yet. The limit is 6 camps however and by level 4  you should have 6 camps regardless of your world. If a level has blueprints it should also have a camp somewhere. Are you sure you've explorted them all? What's your world seed (visible in the import/export menu)?

**Comment by mavion** [comment]
My seed is 4844. I've explored everything on level 6, though I lack 3(I think) spots on level 5 due to extreme cold.
I think the issue might be in line 76 and 98 of WorldCreator.js as the levelordinal of level 6/5 is 8/9 and so the number of camps gets set to 0. I believe the intention there was to use campordinal instead as that is what is used for blueprints.

**Comment by nroutasuo** [comment]
Your assumption was correct, and this'll be fixed in the next update. Thanks for reporting!
